<<<<<<< HEAD
version: '3'

services:
  platinum_cap:
    build: '.'
    env_file:
      - 'client/.env'
    tty: true
    stdin_open: true
    ports:
      - '5000:5000'
=======
version: '3'

services:
  platinum-capital-app:
    build: '.'
    env_file:
      - 'client/.env'
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
>>>>>>> a5a75a8c52ab62e2bd7481d1203a18bbff32e120
